name: CI
on: [push]
jobs:
  eslint:
    name: ESLint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Test
        run: npm run ci:test
