name: CI
on: [push]
jobs:
  eslint:
    name: ESLint and Test
    runs-on: ubuntu-latest

    steps:
      - run: node -v
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"

      - name: Install packages
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run Test
        run: npm run ci:test
